version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: MotorcycleRentalChallenge.API/Dockerfile
    container_name: motorcycle_rental_api
    ports:
      - "8080:8080"      
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=motorcycle_rental;Username=postgres;Password=postgres
    depends_on:
      - db
      - rabbitmq
  
  worker:
    build:
      context: .
      dockerfile: MotorcycleRentalChallenge.Worker/Dockerfile
    container_name: motorcycle_rental_worker
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__DefaultConnection=Host=db;Database=motorcycle_rental;Username=postgres;Password=postgres
        - RabbitMqHost=rabbitmq
    depends_on:
      - db
      - rabbitmq        

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: motorcycle_rental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  rabbitmq-lib:
  rabbitmq-log:
